FROM centos:centos7
MAINTAINER H-TKO

EXPOSE 6379

ENTRYPOINT ["/usr/bin/redis-server"]

Run yum -y update
Run yum -y install vim git wget curl tar sudo
Run yum -y install epel-release
Run yum -y install redis

